sudo: required
language: python
python:
  - "2.7"
  - "3.3"
# Have Travis CI start mongodb and redis for us
services:
  - docker
before_install:
  - docker pull docker.sunet.se/eduid/mongodb:latest
install: python setup.py develop
script: python setup.py test
